services:
  web_server:
    build: .
    ports:
      - ${WEB_SERVER_PORT}:3000
    depends_on:
      - mysql
      - redis
    container_name: 2dam_inventory-webserver
    working_dir: /web
    command: pm2-runtime start pm2.json
    volumes:
      - ./2dam_inventory:/web
  mysql:
    image: mysql:8.0.1
    container_name: 2dam_inventory-mysql
    #restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - TZ=UTC
    volumes:
     - ./data/db/mysql:/var/lib/mysql
     - ./mysql.cnf:/etc/mysql/my.cnf
  redis: 
    image: 'redis'
    container_name: 2dam_inventory-redis
